// Simple humanoid-robot actions — short, drawable, fun to guess.
export const WORDS = [
  "robot waving",
  "robot dancing",
  "robot running",
  "robot jumping",
  "robot sleeping",
  "robot doing a backflip",
  "robot lifting weights",
  "robot drinking coffee",
  "robot reading a book",
  "robot playing guitar",
  "robot riding a bike",
  "robot kicking a ball",
  "robot painting",
  "robot cooking",
  "robot fishing",
  "robot swimming",
  "robot flying",
  "robot falling over",
  "robot crying",
  "robot laughing",
  "robot thinking",
  "robot pointing",
  "robot clapping",
  "robot taking a bow",
  "robot stretching",
  "robot meditating",
  "robot juggling",
  "robot skateboarding",
  "robot surfing",
  "robot skiing",
  "robot boxing",
  "robot saluting",
  "robot giving a hug",
  "robot high five",
  "robot tiptoeing",
  "robot marching",
  "robot crawling",
  "robot climbing a ladder",
  "robot digging",
  "robot sweeping",
  "robot vacuuming",
  "robot watering plants",
  "robot taking a selfie",
  "robot brushing teeth",
  "robot washing dishes",
  "robot doing laundry",
  "robot mowing the lawn",
  "robot raking leaves",
  "robot shoveling snow",
  "robot hammering a nail",
  "robot sawing wood",
  "robot welding",
  "robot charging battery",
  "robot powering off",
  "robot exploding",
  "robot oiling its joints",
  "robot rebooting",
  "robot waving goodbye",
  "robot blowing a kiss",
  "robot shrugging",
  "robot facepalming",
  "robot dabbing",
  "robot moonwalking",
  "robot breakdancing",
  "robot doing yoga",
  "robot doing pushups",
  "robot jumping rope",
  "robot hula hooping",
  "robot ice skating",
  "robot playing drums",
  "robot playing piano",
  "robot playing violin",
  "robot conducting an orchestra",
  "robot singing",
  "robot whistling",
  "robot sneezing",
  "robot yawning",
  "robot tripping",
  "robot tipping over",
  "robot carrying a box",
  "robot pushing a cart",
  "robot delivering a package",
  "robot serving food",
  "robot pouring tea",
  "robot flipping a pancake",
  "robot blowing bubbles",
  "robot flying a kite",
  "robot walking a dog",
  "robot petting a cat",
  "robot planting a tree",
  "robot picking flowers",
  "robot catching a ball",
  "robot throwing a ball",
  "robot shooting hoops",
  "robot doing karate",
  "robot waving a flag",
  "robot holding an umbrella",
  "robot giving a thumbs up",
  "robot scratching its head",
  "robot checking its watch",
  "robot tying its shoes",
  "robot eating a sandwich",
  "robot blowing out candles",
  "robot riding a scooter",
  "robot rowing a boat",
  "robot lifting a barbell",
  "robot doing a cartwheel",
];
