// ~100 simple humanoid-robot action prompts for drawing.
// Kept short and concrete so they're sketchable in 90 seconds.
export const WORDS = [
  'robot waving',
  'robot doing a backflip',
  'robot charging its battery',
  'robot dancing',
  'robot juggling',
  'robot sleeping',
  'robot running',
  'robot jumping',
  'robot sitting on a chair',
  'robot riding a bike',
  'robot drinking coffee',
  'robot reading a book',
  'robot playing guitar',
  'robot kicking a ball',
  'robot taking a selfie',
  'robot watering a plant',
  'robot flexing muscles',
  'robot doing yoga',
  'robot painting a picture',
  'robot flying with a jetpack',
  'robot skateboarding',
  'robot eating pizza',
  'robot holding an umbrella',
  'robot doing push ups',
  'robot waving goodbye',
  'robot giving a thumbs up',
  'robot blowing a bubble',
  'robot riding a skateboard',
  'robot playing drums',
  'robot fishing',
  'robot cooking dinner',
  'robot brushing its teeth',
  'robot wearing a hat',
  'robot carrying a box',
  'robot climbing a ladder',
  'robot swimming',
  'robot surfing',
  'robot meditating',
  'robot sneezing',
  'robot crying',
  'robot laughing',
  'robot pointing at something',
  'robot taking a bow',
  'robot doing a handstand',
  'robot lifting weights',
  'robot throwing a ball',
  'robot catching a ball',
  'robot playing soccer',
  'robot playing basketball',
  'robot shooting an arrow',
  'robot conducting an orchestra',
  'robot singing into a microphone',
  'robot typing on a laptop',
  'robot answering a phone',
  'robot vacuuming the floor',
  'robot mowing the lawn',
  'robot raking leaves',
  'robot shoveling snow',
  'robot building a sandcastle',
  'robot flying a kite',
  'robot blowing out candles',
  'robot opening a gift',
  'robot wearing sunglasses',
  'robot doing a cartwheel',
  'robot tripping over',
  'robot falling asleep',
  'robot stretching',
  'robot scratching its head',
  'robot saluting',
  'robot hugging a cat',
  'robot walking a dog',
  'robot feeding a fish',
  'robot planting a tree',
  'robot watching tv',
  'robot playing chess',
  'robot rolling dice',
  'robot flipping a pancake',
  'robot pouring a drink',
  'robot slicing bread',
  'robot taking out the trash',
  'robot folding laundry',
  'robot ironing a shirt',
  'robot washing dishes',
  'robot riding a scooter',
  'robot roller skating',
  'robot ice skating',
  'robot skiing',
  'robot snowboarding',
  'robot doing karate',
  'robot boxing',
  'robot fencing',
  'robot bowling',
  'robot playing tennis',
  'robot playing golf',
  'robot jumping rope',
  'robot hula hooping',
  'robot riding a unicycle',
  'robot balancing on one foot',
  'robot tip toeing',
  'robot marching',
  'robot pushing a cart',
  'robot pulling a wagon',
  'robot high fiving',
  'robot shaking hands',
  'robot blowing a kiss',
  'robot scratching its back',
  'robot doing the robot dance',
  'robot spinning in circles',
  'robot striking a pose',
  'robot taking a nap',
]

export function randomWord(exclude = []) {
  const pool = WORDS.filter((w) => !exclude.includes(w))
  const list = pool.length ? pool : WORDS
  // Caller seeds randomness; index chosen here.
  return list[Math.floor(Math.random() * list.length)]
}
