// ~100 simple humanoid-robot actions for the drawer to sketch.
export const WORDS = [
  'robot waving',
  'robot doing a backflip',
  'robot charging its battery',
  'robot dancing',
  'robot juggling',
  'robot sleeping',
  'robot running',
  'robot jumping',
  'robot sitting down',
  'robot reading a book',
  'robot drinking coffee',
  'robot playing guitar',
  'robot taking a selfie',
  'robot doing yoga',
  'robot lifting weights',
  'robot riding a bike',
  'robot painting a picture',
  'robot cooking dinner',
  'robot vacuuming',
  'robot watering plants',
  'robot brushing its teeth',
  'robot tying its shoes',
  'robot giving a high five',
  'robot hugging',
  'robot crying',
  'robot laughing',
  'robot thinking hard',
  'robot saluting',
  'robot taking a bow',
  'robot stretching',
  'robot meditating',
  'robot swimming',
  'robot skateboarding',
  'robot surfing',
  'robot skiing',
  'robot climbing a ladder',
  'robot fishing',
  'robot gardening',
  'robot sweeping the floor',
  'robot mopping',
  'robot ironing a shirt',
  'robot folding laundry',
  'robot washing dishes',
  'robot flipping pancakes',
  'robot eating pizza',
  'robot blowing bubbles',
  'robot flying a kite',
  'robot playing chess',
  'robot playing soccer',
  'robot shooting hoops',
  'robot bowling',
  'robot playing golf',
  'robot boxing',
  'robot doing karate',
  'robot breakdancing',
  'robot moonwalking',
  'robot conducting an orchestra',
  'robot playing drums',
  'robot playing piano',
  'robot singing',
  'robot whistling',
  'robot sneezing',
  'robot yawning',
  'robot waking up',
  'robot falling over',
  'robot tripping',
  'robot dancing ballet',
  'robot doing the robot dance',
  'robot rollerblading',
  'robot jumping rope',
  'robot hula hooping',
  'robot doing push-ups',
  'robot doing sit-ups',
  'robot planking',
  'robot cartwheeling',
  'robot pointing',
  'robot clapping',
  'robot snapping its fingers',
  'robot scratching its head',
  'robot shrugging',
  'robot facepalming',
  'robot flexing muscles',
  'robot striking a pose',
  'robot blowing a kiss',
  'robot giving a thumbs up',
  'robot crossing its arms',
  'robot checking its watch',
  'robot reading a map',
  'robot using a phone',
  'robot typing on a laptop',
  'robot writing a letter',
  'robot taking out the trash',
  'robot walking a dog',
  'robot pushing a shopping cart',
  'robot carrying groceries',
  'robot opening an umbrella',
  'robot dancing in the rain',
  'robot riding a unicycle',
  'robot juggling torches',
  'robot doing jumping jacks',
  'robot tiptoeing',
  'robot waving goodbye',
]
